### ISSUE TITLE
Refactor callback concept

### ISSUE THREAD

**Issue by heshamMassoud** [commercetools/commercetools-sync-java#107]
Callback should support returning boolean. This is to support the use case of continuing  or not when one update action building fails. Should the entire product/category still be synced with the rest of the successful update actions or not.

Right now, if one update action fails, the callback would be applied but the rest of the update actions for the product would still be applied.

1. Change name warningCallBack -> validationCallback (or draftValidationCB, dataValidationCB, syncValidationCb, etc..)
   - Extend param list to be: `(Enum ErrorType, String errorMessage, T oldResource, S newDraft)`
2. Change name of errorCallback -> ctpErrorCalback
   - Extend param list to be: `(String errorMessage, T oldResource, S newDraft, Throwable exception)` 
3. Need to think about the continue on errors concept.. 
4. Also see issue: https://github.com/commercetools/commercetools-sync-java/issues/50 and 

----------
###### Update
Referencing TODOs from https://github.com/commercetools/commercetools-sync-java/issues/336#issuecomment-442891974:
- Difference between events causing `errorCallback` and `warningCallback` should be clearly defined and documented. 
- errorCallback exceptions should not be `nullable`. It should always have an exception object. (Think about removing the `errorMessage` String)

**Comment by butenkor** [comment]
> Extend param list to be: (Enum ErrorType, String errorMessage, T oldResource, S newDraft)

Suggestion as discussed (exception would be a subtype of `SyncException` and also contain detailed error message):

`(SyncException se, T oldResource, S newDraft)`

**Comment by jarzynp** [comment]
Hi @heshamMassoud 
If you agree I'd like to implement this - maybe it will be sufficient enough (instead of #336), but have some questions:

1. Return value
> Callback should support returning boolean

Does this apply only to the error callback or to warning one as well?


2. Update action
> This is to support the use case of continuing or not when one update action building fails. Should the entire product/category still be synced with the rest of the successful update actions or not.

What `update action` really means? For example: ProductType:
- when creating we are using `ProductTypeCreateCommand` which accepts `ProductTypeDraft` as parameter
- when updating we are using `ProductTypeUpdateCommand` which accepts versioned product type and list of `UpdateAction<>`
When there will be error during processing on target side, all successful operations up to this moment will be reverted - it doesn't matter if it happened during creation or updating and exception will be returned - so there is no possibility to continue with `UpdateAction<>` which were not processed yet.
But sync process will be continued with another resource draft (if any). Does the `update action` in this context mean a single Resource update (a batch unit)? Please clarify that as the `update action` can be misleading (possibly confused with the `UpdateAction` class). 

By resource draft I understand one list item passed to this methods: `BaseSync#sync(@Nonnull final List<T> resourceDrafts)` or `BaseSync#process(@Nonnull final List<T> resourceDrafts)`

3. Parameter order
What should be order of parameters oldResource and newResourceDraft:
a. proposed: `T oldResource, S newDraft`
b. consistent with `beforeUpdateCallback`: `S newDraft, T oldResource`

4. SyncException
What is `SyncException` mentioned by @butenkor ? Is this a new class which is not yet in sources (some branch maybe) or it has to be created? If the latter what it should contain?

5. Exception and message
Maybe it would be good to replace parameters `String errorMessage` and `Throwable exception` by some aggregation class, `SyncException` maybe? Maybe context related data (oldResource, newDraft) should be also in `SyncException`?

**Comment by heshamMassoud** [comment]
Hi, @jarzynp, of course! that would be great :)

> 1. Does this apply only to the error callback or to warning one as well?

I think It would be useful if we return `boolean` on both callbacks. So the user is more flexible to choose when to stop the sync process (even if on a warning use case). WDYT? (cc: @butenkor)

> 2. This is to support the use case of continuing or not when one update action building fails. Should the entire product/category still be synced with the rest of the successful update actions or not. What update action really means? For example: ProductType:

Sorry, the issue was described in a rush. Let me try to rephrase a bit:

The `errorCallback` could be triggered at many places during syncing each `productTypeDraft`, this includes:
1. While building enum value update actions (e.g. `removeEnumValues`, `addPlainEnumValue`, etc..) for a productType's attribute that will be used later in an update request. If the supplied enum in the `productTypeDraft` has duplicate keys.
2. While issuing an update request to CTP due to a `400`, or even a `5xx` after retrying, etc..
3. While issuing a create request to CTP due to a `400`, or even a `5xx` after retrying, etc..

It could be that the user would want to selectively choose if he/she wants to continue the sync process or actually continue after such error occurs. 

> But sync process will be continued with another resource draft (if any). Does the update action in this context mean a single Resource update (a batch unit)? Please clarify that as the update action can be misleading (possibly confused with the UpdateAction class).

> By resource draft I understand one list item passed to this methods: BaseSync#sync(@Nonnull final List<T> resourceDrafts) or BaseSync#process(@Nonnull final List<T> resourceDrafts)

Yes, by that we mean with one resource draft error. For example one `productTypeDraft`.


> 3. What should be order of parameters oldResource and newResourceDraft:
a. proposed: T oldResource, S newDraft
b. consistent with beforeUpdateCallback: S newDraft, T oldResource

Good point. In that sense, **b** sounds more user-friendly. But all the update action utils have the ordering of **a* 😢 WDYT? (cc: @butenkor)

> 4. & 5. What is SyncException mentioned by @butenkor ? Is this a new class which is not yet in sources (some branch maybe) or it has to be created? If the latter what it should contain? 

No, it doesn't exists _yet_. It is a proposal to have a kind of a parent `Throwable` type that has a cause (which could be anything e.g. `SphereException` from the platform, or `BuildUpdateException` from the library, etc..

**Comment by butenkor** [comment]
> So the user is more flexible to choose when to stop the sync process

I am not sure if return value is necessary as the caller can throw own exception to break sync execution - if needed. If callback is defined in the same class where the sync instance is created then one could also catch own error an eventually also access/log sync statistics from existing sync instance.

> b sounds more user-friendly

indeed :)

**Comment by jarzynp** [comment]
Ok, so what's the final decision for return value?
1. Return value for both callbacks
2. Return value only for errorCallback
3. Return value only for warningCallback
4. No return value for both callbacks

**Comment by butenkor** [comment]
Hi @jarzynp,

here is polished version of my previous comment :)

> Ok, so what's the final decision for return value?

For now we do not have clear business use-case so let's just take option 4 and apply other suggested changes:

As discussed, an exception would be a subtype of `SyncException` and also contain detailed error message.

**errorCallback**:
- `(SyncException se, T oldResource, S newDraft, Optional<List<UpdateAction<T>>>)`
- Let's also keep old name: `errorCallback`

**warningCallback**
- `(SyncException se, T oldResource, S newDraft)`
- Let's also keep old name: `warningCallback`

@heshamMassoud You agree?

**Comment by heshamMassoud** [comment]
@jarzynp Yes, I agree with @butenkor. We can leave the the return value / continue on errors concept as another issue/feature 😉

**Comment by jarzynp** [comment]
Hi,

PR ready for review: https://github.com/commercetools/commercetools-sync-java/pull/367

Happy New Year! :)

**Comment by heshamMassoud** [comment]
Besides checking existing PR comments and addressing conflicts, make sure that we use a context object which is propagated everywhere needed down the update actions utils, so that we can get the old and new resources deep down the method chain without the need of applying workarounds (e.g. [the generic types of the util class](https://github.com/commercetools/commercetools-sync-java/pull/367/files?file-filters%5B%5D=.java#diff-cea7e36a8d3c43856febd3c4d36f8145R142)).

The idea is to propagate to the callback the whole resource (new or old) and not just failed sub resource (e.g. assets, prices, etc..)

**Comment by ahmetoz** [comment]
Released with: https://github.com/commercetools/commercetools-sync-java/blob/master/docs/RELEASE_NOTES.md#200---sept-14-2020
