### ISSUE TITLE
Link Javadoc from README (prominently)

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-sync-java#145]
### Description
To make it easier to start with, prominently link to the JavaDoc from the README.md

 e.g. like done in the JVM SDK https://github.com/commercetools/commercetools-jvm-sdk 

### Context

We learnt this "the hard way" in the JVM SDK - if you don't put a very prominent link nobody reads al the hard work you have put in the JavaDocs.  Had to send out the link separately to everybody.

**Comment by heshamMassoud** [comment]
@nkuehn it's there actually: https://github.com/commercetools/commercetools-sync-java#commercetools-sync 
The last point in the TOC.. Maybe it's not very visible?

**Comment by nkuehn** [comment]
Probably not prominent enough - at least I oversaw it.    
Same learning with the JVM SDK, seems like you have to really put a  big button on the top of it to move users into the JavaDoc instead of reading the README which is focused on developers of the library.

**Comment by heshamMassoud** [comment]
@nkuehn https://github.com/commercetools/commercetools-sync-java#commercetools-sync It's now added as a badge in the main readme :) 

> instead of reading the README which is focused on developers of the library.
The dev contributing stuff are moved away now from the main readme. They are now in the [CONTRIBUTING](https://github.com/commercetools/commercetools-sync-java/blob/master/docs/CONTRIBUTING.md). So that the main readme is only focused on the users of the lib.

**Comment by heshamMassoud** [comment]
Closing this issue now since it should be addressed by 5d72274.
