### ISSUE TITLE
Remove CtpQueryUtils and use impl from JVM-SDK v1.25.0

### ISSUE THREAD

**Issue by heshamMassoud** [commercetools/commercetools-sync-java#158]
Remove CtpQueryUtils and use impl from JVM-SDK v1.25.0

**Comment by ahmetoz** [comment]
That task is a bit outdated when we compare the QueryExecutionUtils(in SDK) and CtpQueryUtils in sync. Also, it would be a breaking change for the users of the library as they might also use our examples in docs. Another reason there is no real benefit to changing this for now because we need to move all our new logic to SDK again, which is probably not on our to-do list right now. So I am closing this out of data issue.
