### ISSUE TITLE
Use builders for Reference resolvers

### ISSUE THREAD

**Issue by heshamMassoud** [commercetools/commercetools-sync-java#174]
Since the reference resolvers are getting bigger and bigger, and their constructors are getting more services injected into them. It makes sense now to introduce builders to the reference resolvers, to have an extensible and more consistent design.

Ideally, the builders could be abstracted to be used by several reference resolvers.

Please check more here: where it was first suggested by @andrii-kovalenko-ct : https://github.com/commercetools/commercetools-sync-java/pull/167#discussion_r147345291

**Comment by ahmetoz** [comment]
IMO doing an injection in the constructor is better than using a builder when it comes to testing and the DI principle.
The resolvers are getting bigger because there are lots of references, so services that need to be used in that resolvers, so I'm seeing that natural.. also it's hard to reason to get an argument in the old PR, this issue looks like waiting for a response for a long time, I am closing it.
