### ISSUE TITLE
Investigate SonarCloud, SonarJava

### ISSUE THREAD

**Issue by heshamMassoud** [commercetools/commercetools-sync-java#214]
[![Quality Gate](https://sonarcloud.io/api/badges/gate?key=com.commercetools:commercetools-sync-java)](https://sonarcloud.io/dashboard?id=com.commercetools%3Acommercetools-sync-java)

**Comment by aepfli** [comment]
well i was bored, so i looked for github projects with gradle as build tool and sonarcloud analysis as a goal. do you still need help regarding this, i could provide a pull request with a solution also utilitizing travisCI properties etc. ;) just let me know if this issue is still valid

**Comment by ahmetoz** [comment]
Hi @aepfli sorry for the late reply on the issue, we have not discussed lately to use an external tool for code analysis for this library, so it's not our goal in the near future, the issue is opened as an investigation, and we could not complete it and looks like not maintained after,  but if you have time for this you might create a PR and we could consider it.
