### ISSUE TITLE
Copying one Commercetools project into another with same contents

### ISSUE THREAD

**Issue by eshwaravadanula** [commercetools/commercetools-sync-java#285]
Hi,

This is Eshwar from Express Inc, USA.

This is not an issue or idea, I just want to understand/know if there is an easy way to copy the whole Commercetools project into another Commercetools Project.

Scenario: We have 'ABC' Commercetools project in Production, in case of any issues/bugs/functionality check we need to copy the whole 'ABC' project into another 'DEF' project with exact same contents (Products, ProductTypes, Prices etc).

I have tried going thru some of the code in commercetools-sync-java project but not able to find the quick way of copying the whole project into another.

Please help me with some code snippets or classes if we can achieve this functionality.

Thanks
Eshwar

**Comment by heshamMassoud** [comment]
Hi @eshwaravadanula thanks for opening the issue.

Currently, it is still not possible to copy the **entire** commercetools project to a target commercetools project. 

As mentioned in the [README here](https://github.com/commercetools/commercetools-sync-java#usage), the library supports **categories**, **products** (with prices) and **inventory entries**. **ProductTypes** sync is currently a work in progress and will be released very soon! 

The library allows you to sync each resource separately rather than the entire resources of a project. For example to sync a list of `ProductDraft`s to a target commercetools project like that:

````java
// instantiating a product sync
final ProductSync productSync = new ProductSync(productSyncOptions);

// execute the sync on your list of products
CompletionStage<ProductSyncStatistics> syncStatisticsStage = productSync.sync(productDrafts);
````

You can find more details about the prerequisites of the snippet here: https://github.com/commercetools/commercetools-sync-java/blob/master/docs/usage/PRODUCT_SYNC.md#usage

Here are some integration tests which exactly do your use case of syncing products from a source commercetools project to a target project: 

https://github.com/commercetools/commercetools-sync-java/blob/master/src/integration-test/java/com/commercetools/sync/integration/ctpprojectsource/products/ProductSyncIT.java#L201-L206

**Comment by nkuehn** [comment]
Hi Eshwar,  afaik you or your colleagues are in contact with our team directly to get support - the use case you are describing can be done by us for you. Either write a support issue on the portal or contact the person that is consulting you anyways.   Please keep in mind that such "raw" project copies are typically not a good idea for the everyday development process - it's a partly manual process and the copy contains all transactions, user data, message history etc. which you mostly don't want for development purposes.   So in the long run it's worth doing up an own scripted setup that syncs only exactly what you need for development. 

You can also take a look at the sync support of the Javascript SDK - it covers a different set of our APIs for syncing data between data sources https://commercetools.github.io/nodejs/sdk/api/syncActions.html

**Comment by heshamMassoud** [comment]
@eshwaravadanula I hope the comments above have you helped you achieve the desired function. Closing this issue.
