### ISSUE TITLE
Should retry on API errors like 5xx

### ISSUE THREAD

**Issue by butenkor** [commercetools/commercetools-sync-java#31]
Affects all modules (should be covered by JVM SDK)

**Comment by jakubchrobak** [comment]
**Proposed solution**:
- provide utility function which wraps a sphere client in [RetrySphereClientDecorator](http://commercetools.github.io/commercetools-jvm-sdk/apidocs/io/sphere/sdk/client/RetrySphereClientDecorator.html)
- use that function in a services' constructors (cause they are responsible for performing CRUD operations on CTP and they take a `sphereClient` as a parameter)

@butenkor I'm not sure about the strategy regarding calculation of waiting time between subsequent retry attemps. Could you provide me expected numbers so that it was reasonable?
E.g. Would a sequence `2s, 2s, 2s, 4s, 4s, 4s, ... , 512s, 512s, 512s` of waiting time between following attempts be ok? It would result in 26 attempts, lasting almost 2 hours in a case of the constant failure.

**Comment by heshamMassoud** [comment]
Doesn't have to be a responsibility of the sync library. Showing an example in integration tests should be enough.
