### ISSUE TITLE
Category to CategoryDraft Transformation

### ISSUE THREAD

**Issue by heshamMassoud** [commercetools/commercetools-sync-java#9]
Implement DraftTransformer which converts:-
- [ ]  a `Category` to a `CategoryDraft` .
- [ ]   a list of `Category`s to a list of `CategoryDraft`s. 
- [ ]   a `CustomFields` to a `CustomFieldsDraft`.
- [ ]   a `Category` to a `CategoryDraft`, given a cache of the type keys->internal ids.
- [ ]   a list of `Category`s to a list of `CategoryDraft`s, given a cache of the type keys->internal ids.
- [ ]   a `CustomFields` to a `CustomFieldsDraft`, given a `key` of the `Type`.
- [ ]   a `Asset` to an `AssetDraft`.
- [ ]   a list of `Asset`s to a list of `AssetDraft`s.
    

> In the cases, where the cache of the Type keys is not provided, the sync would expect that reference expansion is already done and would try to get the key from the expanded object. The caching options are there to encourage the users of the sync module not to do reference expansion which degrades performance.( //cc @butenkor could you please double check on this)

- [ ] The above note should be well documented in JavaDocs and in the README of the DraftTransformer/sync module.

for the above methods, the following should be done:
- [ ] Unit tests 
- [ ] Integration tests
- [ ] JavaDocs

**Comment by nkuehn** [comment]
if you don't get SDK level support for this and don't want to run into a never ending maintenance hell to add new fields you could consider implementing this "catch all" via the existing Jackson serialization / deserialization. 

If you don't serialize to JSON string, but just to the java JsonNode I am pretty sure that the performance overhead is low, too. 
```JsonNode node = objectMapper.valueToTree(myObject);```

Caveat:  Products need special consideration since the draft has a different high-level structure than the Product.

**Comment by heshamMassoud** [comment]
Should be built-in SDK. See issue #12 last comments.

**Comment by katmatt** [comment]
@heshamMassoud That's what I already build 👍 Meaning: our code generator builds it for us, but currently only for the classes that you mentoned.

And I hope that we can release it this week 😉
